function [ x ] = initialize_truth_state( simpar )
%initialize_truth_state initialize the truth state vector consistent with
%the initial covariance matrix
%
% Inputs:
%   No Inputs
%
% Outputs
%   Output1 = truth state vector
%
% Example Usage
% [ output_args ] = initialize_truth_state()

% Author: Sam Christensen
% Date: 31-Aug-2020 15:46:59
% Reference: 
% Copyright 2020 Utah State University

% In the initialization of the truth and navigation states, you need only
% ensure that the estimation error is consistent with the initial
% covariance matrix.  One realistic way to do this is to set the true 
% vehicle states to the same thing every time, and randomize any sensor 
% parameters.

ic = simpar.general.ic;
quaternion = euler2quat(ic.th_x, ic.th_y, ic.th_z);
x = [ic.ri_x;...
     ic.ri_y;...
     ic.ri_z;...
     ic.vi_x;...
     ic.vi_y;...
     ic.vi_z;...
     quaternion(1,:);...
     quaternion(2,:);...
     quaternion(3,:);...
     quaternion(4,:);...
     ic.steer_ang;...
     ic.accl_bias_x;...
     ic.accl_bias_y;...
     ic.accl_bias_z;...
     ic.gyro_bias_x;...
     ic.gyro_bias_y;...
     ic.gyro_bias_z;...
     ic.crumb_pos_x;...
     ic.crumb_pos_y;...
     ic.crumb_pos_z;];

end
